#pragma once

#include <cstdint>

// Auto-generated by firmware/tools/gen_object_pool.py -- do not hand-edit.
// Object ID constants matching object_pool.iop. See docs/vt-ui-design.md.

namespace iso::object_pool_ids {

constexpr uint16_t kWorkingSet = 1000;
constexpr uint16_t kDataMask = 1100;
constexpr uint16_t kConfigDataMask = 1300;
constexpr uint16_t kConfigNameMaxChars = 8;
constexpr uint16_t kSoftKeyMask = 1200;
constexpr uint16_t kSoftKeyMask2 = 1201;
constexpr uint16_t kSoftKeyMask3 = 1202;
constexpr uint16_t kSoftKeyMaskConfig = 1203;
constexpr uint16_t kTitleString = 1101;
constexpr uint16_t kTitleStringMaxChars = 44;

constexpr uint16_t kSoftkeyNext3 = 1266;
constexpr uint16_t kSoftkeyBack3 = 1267;
constexpr uint16_t kSoftkeyConfig = 1268;
constexpr uint16_t kSoftkeyConfigBack = 1270;
// Touch Button on the main Data Mask (second entry point to the CFG view).
constexpr uint16_t kConfigButton = 1272;
// Channel names are shortened to this many characters on soft keys / AUX-N lists.
constexpr uint16_t kKeyLabelMaxChars = 7;

// WiFi status/control panel (page 3) -- see net/wifi_ap.hpp.
constexpr uint16_t kSoftkeyWifiToggle = 1264;
constexpr uint16_t kWifiEnabledFillAttr = 1941;
constexpr uint16_t kWifiSsidLabel = 1144;
constexpr uint16_t kWifiPasswordInput = 1145;
constexpr uint16_t kWifiIpLabel = 1146;
constexpr uint16_t kWifiClientsLabel = 1147;
constexpr uint16_t kWifiPasswordMaxChars = 32;

// channel: 1-8
inline uint16_t relay_rect_id(int channel) { return 1110 + channel; }
inline uint16_t relay_fill_attr_id(int channel) { return 1920 + channel; }
inline uint16_t relay_label_id(int channel) { return 1120 + channel; }
inline uint16_t config_name_input_id(int channel) { return 1320 + channel; }
inline uint16_t softkey_label_id(int key_number) { return 1230 + key_number; }
inline uint16_t aux_latch_label_id(int channel) { return 1540 + channel; }
inline uint16_t aux_momentary_label_id(int channel) { return 1550 + channel; }
inline uint16_t softkey2_label_id(int channel) { return 1280 + channel; }
inline uint16_t di_fill_attr_id(int channel) { return 1930 + channel; }

// key_number: 1-8 = relay channels (toggle), 9 = buzzer, 10 = next page
inline uint16_t softkey_id(int key_number) { return 1210 + key_number; }

// Soft Key Mask page 2: channel 1-8 = momentary override, plus a back key.
inline uint16_t softkey2_id(int channel) { return 1250 + channel; }
constexpr uint16_t kSoftkeyBack = 1260;
constexpr uint16_t kSoftkeyOverrideToggle = 1262;
constexpr uint16_t kOverrideCheckboxFillAttr = 1940;

// AUX-N Auxiliary Function Type 2 objects. channel: 1-8.
inline uint16_t aux_latch_function_id(int channel) { return 1500 + channel; }
inline uint16_t aux_momentary_function_id(int channel) { return 1520 + channel; }
constexpr uint16_t kAuxBuzzerFunction = 1560;

}  // namespace iso::object_pool_ids
